feat!: API-406: Replaced input fail_on_lint_error with new fail_threshold  (#48)
* feat!: API-406: Replaced inputs fail_on_lint_error and fail_on_lint_warning with new input fail_threshold

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -18,10 +18,10 @@ on:
         description: "If true, will upload the spec(s) to a GCS bucket for analytics."
         type: boolean
         default: true
-      fail_on_lint_error:
-        description: "If true, a lint error will fail the workflow."
-        type: boolean
-        default: false
+      fail_threshold:
+        description: "The threshold to fail the build. Accepted values: warn, error, never"
+        type: string
+        default: 'never'
 
 jobs:
   validate-input:
@@ -41,6 +41,16 @@ jobs:
             echo "Error: Both spec and artifact were provided. Please provide only one."
             exit 1
           fi
+          
+          # Validate fail_threshold
+          case "${{ inputs.fail_threshold }}" in
+            warn|error|never) 
+              ;;  # OK
+            *) 
+              echo "Error: fail_threshold must be one of: warn, error, never"
+              exit 1
+              ;;
+          esac
   lint:
     name: OpenAPI Lint
     runs-on: ubuntu-latest
@@ -93,6 +103,7 @@ jobs:
           total_count=$(jq 'length // 0' "$tmp")
           #Error issues
           error_count=$(jq '[.[] | select(.severity == 0)] | length' "$tmp")
+          warning_count=$(jq '[.[] | select(.severity == 1)] | length' "$tmp")
           
           #) Get workspace root so we can strip it
           ws="${GITHUB_WORKSPACE%/}"          
@@ -126,8 +137,13 @@ jobs:
               echo "No issues found." >> "$GITHUB_STEP_SUMMARY"
             fi
                         
-            if [ "$error_count" -gt 0 ] && [ "${{ inputs.fail_on_lint_error }}" != "false" ]; then
+            if [ "$error_count" -gt 0 ] && [ "${{ inputs.fail_threshold }}" != "never" ]; then
               echo "❌ Found linting errors. Failing workflow." >&2
+              exit 1
+            fi                       
+          
+            if [ "$warning_count" -gt 0 ] && [ "${{ inputs.fail_threshold }}" = "warn" ]; then
+              echo "❌ Found linting warnings. Failing workflow." >&2
               exit 1
             fi
 
