fix: API-407 cleanup (#54)
* fix: API-407: Improved logging. Quoting variables used in shell commands.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -30,15 +30,19 @@ jobs:
     steps:
       - name: Validate inputs
         run: |
+          set -o errexit  #Exits immediately if any command fails (returns non-zero)
+          set -o nounset  #Treats unset variables as errors          
+          set -o pipefail #Makes a pipeline fail if any command in it fails (not just the last)
+          
           # Ensure not both inputs are empty.
           if [ -z "${{ inputs.artifact }}" ] && [ -z "${{ inputs.spec }}" ]; then            
-            echo "Error: Exactly one of spec OR artifact is required."
+            echo "::error::Exactly one of spec OR artifact is required."
             exit 1
           fi          
 
           # Ensure not both inputs are provided.
           if [ -n "${{ inputs.artifact }}" ] && [ -n "${{ inputs.spec }}" ] && [ "${{ inputs.spec }}" != "specs/*.json" ]; then            
-            echo "Error: Both spec and artifact were provided. Please provide only one."
+            echo "::error::Both spec and artifact were provided. Please provide only one."
             exit 1
           fi
 
@@ -47,7 +51,7 @@ jobs:
             warn|error|never) 
               ;;  # OK
             *) 
-              echo "Error: fail_threshold must be one of: warn, error, never"
+              echo "::error::fail_threshold must be one of: warn, error, never"
               exit 1
               ;;
           esac
@@ -80,7 +84,11 @@ jobs:
         run: npm install -g @stoplight/spectral-cli
       - name: Lint OpenAPI
         shell: bash
-        run: |
+        run: |          
+          set -o errexit
+          set -o nounset
+          set -o pipefail
+          
           shopt -s globstar
 
           if [ -n "${{ inputs.artifact }}" ]; then
@@ -90,8 +98,8 @@ jobs:
           fi          
 
           #This is needed, because calling spectral with a glob that does not match any files will succeed, which is not what we want.
-          if ! compgen -G $spec_glob > /dev/null; then
-            echo "No file matches '$spec_glob'"
+          if ! compgen -G "$spec_glob" > /dev/null; then
+            echo "::error::No file matches '$spec_glob'"
             exit 1
           fi            
 
@@ -124,7 +132,7 @@ jobs:
                  else (.severity|tostring) end) as $sev |
                 # collapse JSON-path array into dot-path
                 (.path | join(".")) as $jsonPath |
-                # build start/end as “line:char”
+                # build start/end as "line:char"
                 "\(.range.start.line):\(.range.start.character)" as $start |
                 "\(.range.end.line):\(.range.end.character)"   as $end |
                 # strip the workspace prefix from source
@@ -138,12 +146,12 @@ jobs:
             fi
                         
             if [ "$error_count" -gt 0 ] && [ "${{ inputs.fail_threshold }}" != "never" ]; then
-              echo "❌ Found linting errors. Failing workflow." >&2
+              echo "::error:: Found linting errors. Failing workflow."
               exit 1
             fi                       
 
             if [ "$warning_count" -gt 0 ] && [ "${{ inputs.fail_threshold }}" = "warn" ]; then
-              echo "❌ Found linting warnings. Failing workflow." >&2
+              echo "::warning::Found linting warnings. Failing workflow."
               exit 1
             fi
 
@@ -182,6 +190,9 @@ jobs:
         uses: google-github-actions/setup-gcloud@v2
       - name: Copy specs to temporary directory
         run: |
+          set -o errexit
+          set -o nounset
+          set -o pipefail
           shopt -s globstar
 
           mkdir -p /tmp/specs
@@ -194,5 +205,8 @@ jobs:
           fi
       - name: Upload specs to GCS
         run: |
+          set -o errexit
+          set -o nounset
+          set -o pipefail
           echo "Starting to sync files in /tmp/specs/ to GCS Bucket to path /${GITHUB_REPOSITORY#*/}"
           gcloud storage rsync /tmp/specs/ "gs://ent-gcs-api-specs-prd-001/${GITHUB_REPOSITORY#*/}"
