feat: Add support for bundling (using redocly)

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -10,6 +10,10 @@ on:
         description: "Artifact containing the OpenAPI specification."
         type: string
 
+env:
+  REDOCLY_VERSION: "2.25.1"
+  SPECTRAL_VERSION: "6.15.0"
+
 jobs:
   evaluate-input:
     name: Evaluate input
@@ -64,7 +68,6 @@ jobs:
       - name: Validate spec
         shell: bash
         env:
-          SPECTRAL_VERSION: "6.15.0"
           GHA_API_PATH:     ${{ needs.evaluate-input.outputs.spec_path }}
         run: |
           set -o errexit
@@ -74,6 +77,11 @@ jobs:
 
           if ! npx @stoplight/spectral-cli@$SPECTRAL_VERSION lint "$GHA_API_PATH" --ruleset "rulesets/.spectral-required.yml"; then
             echo "::error::Spec validation failed. Failing workflow."
+            exit 1
+          fi  
+
+          if ! npx @redocly/cli@$REDOCLY_VERSION bundle $GHA_API_PATH; then
+            echo "::error::Spec bundling failed. Failing workflow."
             exit 1
           fi  
 
@@ -96,7 +104,9 @@ jobs:
         with:
           name: ${{ inputs.artifact }}
           path: /tmp/artifact
-
+      - uses: actions/setup-node@v6
+        with:
+          node-version: 24
       - name: Authenticate with Google Cloud
         id: auth
         uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
@@ -110,14 +120,18 @@ jobs:
 
       - name: Upload
         env:
-          GHA_API_PATH: ${{ needs.evaluate-input.outputs.spec_path }}
-          ID_TOKEN:     ${{ steps.auth.outputs.id_token }}
+          GHA_API_PATH:    ${{ needs.evaluate-input.outputs.spec_path }}
+          ID_TOKEN:        ${{ steps.auth.outputs.id_token }}
         shell: bash
         run: |
           set -o errexit
           set -o nounset
           set -o pipefail
           shopt -s globstar
+
+          filename=$(basename $GHA_API_PATH)
+          mkdir -p /tmp/specs
+          npx @redocly/cli@$REDOCLY_VERSION bundle -o /tmp/specs/$filename $GHA_API_PATH
 
           # Extract repository name (without owner)
           REPO_NAME="${GITHUB_REPOSITORY#*/}"
@@ -126,12 +140,12 @@ jobs:
           METADATA="{\"repository\": \"$REPO_NAME\"}"
 
           echo "Publishing spec: $GHA_API_PATH"
-              
+          
           curl --fail-with-body -sS \
             -X PUT \
             -H "Authorization: Bearer $ID_TOKEN" \
             -F "metadata=$METADATA;type=application/json" \
-            -F "spec=@$GHA_API_PATH" \
+            -F "spec=@/tmp/specs/$filename" \
             "$CLOUD_RUN_ENDPOINT"
-              
+          
           echo "Successfully published: $GHA_API_PATH"
