API-281: Exit code success if no changes to specs

diff --git a/.github/workflows/store-api-spec-lint-results.yml b/.github/workflows/store-api-spec-lint-results.yml
--- a/.github/workflows/store-api-spec-lint-results.yml
+++ b/.github/workflows/store-api-spec-lint-results.yml
@@ -73,8 +73,8 @@ jobs:
           
           # If no spec file has changed, exit the workflow.
           if [ ${#changed_specs[@]} -eq 0 ]; then
-            echo "No spec changes detected. Exiting workflow."
-            exit 0
+            echo "No spec changes detected. Exiting workflow. (This is not an error.)"
+            exit 1
           fi
           
           # Convert the array of changed spec files into a space-separated string.
